name: pdf_reader
description: A Flutter PDF Reader app similar to PixPDF
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # PDF handling
  flutter_pdfview: ^1.3.2
  pdf: ^3.10.7
  path_provider: ^2.1.1
  file_picker: ^8.0.0+1
  
  # UI and navigation
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  
  # Image handling
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # Sharing and permissions
  share_plus: ^7.2.1
  permission_handler: ^11.0.1
  
  # UI components
  shimmer: ^3.0.0
  supabase_flutter: ^2.10.3
  in_app_purchase: ^3.2.3
  firebase_core: ^4.2.0
  firebase_analytics: ^12.0.3
  firebase_crashlytics: ^5.0.3
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  http: ^1.5.0
  dio: ^5.9.0
  firebase_performance: ^0.11.1+1
  firebase_remote_config: ^6.1.0
  
  # Ads
  google_mobile_ads: ^5.1.0
  # applovin_max: ^1.0.0  # Temporarily disabled due to build issues
  
  # URL Launcher
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
